
# user  nginx;
# worker_processes  auto;

# error_log  /var/log/nginx/error.log notice;
# pid        /var/run/nginx.pid;


# events {
#     worker_connections  1024;
# }


# http {
#     include       /etc/nginx/mime.types;
#     default_type  application/octet-stream;

#     log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
#                       '$status $body_bytes_sent "$http_referer" '
#                       '"$http_user_agent" "$http_x_forwarded_for"';

#     access_log  /var/log/nginx/access.log  main;

#     sendfile        on;
#     #tcp_nopush     on;

#     keepalive_timeout  65;

#     #gzip  on;

#     include /etc/nginx/conf.d/*.conf;
# }
worker_processes 1;

events {
    worker_connections 1024;
}

http {

    log_format main
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
    include mime.types;

    upstream nodejs_cluster {
        least_conn;
        server nginx-web-app1:3000;
        server nginx-web-app2:3000;
        server nginx-web-app3:3000;
    }
    server {
        listen 8080;
        location /new {
            root /usr/src;
        }
        # when specifying root to serve static files -> according to above conf -> the files should be /usr/src/new & then we can type in the fileName with extension after / (defaults to index.html)
        location /whatever {
            alias /usr/src/new;
        }
        # adding aliases

        server_name localhost;
        location / {
            proxy_pass http://nodejs_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Request-Id $request_id;

            # root <pathToHtml> <- this approach can be used to directly serve static files
        }
    }
}

# logs - check out commented code